### ISSUE TITLE
Broken serial output on Arduino101

### ISSUE THREAD

**Issue by lispler** [quark-mcu/qmsi#7] opened 2016-09-09 11:43 UTC
I've been using QMSI to program the Arduino101, but recent QMSI-1.1 ROM apparently broke the serial output. I have not investigated further, but the attached patch makes it work again for me.

As far as I know, QMSI is the only way right now to create a bootrom for Arduino101: https://jira.zephyrproject.org/browse/ZEP-433

[rom_serial.patch.txt](https://github.com/quark-mcu/qmsi/files/463854/rom_serial.patch.txt)

**Comment by lispler** [comment] 2016-09-09 11:58
I also have to remove boot_sense_jtag_probe() in order to make it run via openocd 'reset run' command. Otherwise only the master reset button works, which requires physical intervention. Not sure if this is related to above or if there is a different way to seamlessly flash&run applications via gdb/jtag.

**Comment by mprinn** [comment] 2016-09-09 12:31
@lispler , when you say it breaks the serial output, is it that the serial output is still occuring but the timing of it is incorrect? if so, it may be that the new rom uses the silicon oscillator mode, try adding a call to clk_sys_set_mode(CLK_SYS_CRYSTAL_OSC,1) call at the start.

If this fixes it, then the issue is that the arduino 101 has some data inside where the new rom is expecting to find TRIM data for the hybrid oscillator, and if i recall correctly the fix is to do a mass erase and then flash the rom again and it will then calculate and populate the correct trim values and the uart should work again.

as for removing boost_sense_jtag_probe, that will just spin if the JTAG pin is grounded, so shouldn't really affect openocd  vs pushing a button manually.

**Comment by jsels** [comment] 2016-09-09 12:34
Be also aware that removing boost_sense_jtag_probe can brick your board. You won't for example be able to recover the board, if you go immediately into deep sleep and never wake-up.

**Comment by jeez** [comment] 2016-09-09 13:36
All of the previous comments make sense. Also please note Arduino 101 has its own bootloader and I believe it is hosted here: https://github.com/CurieBSP/bootloader .

We haven't fully tested the QMSI bootloader on Arduino 101 before, but it looks related to what Malcolm says. The XTAL OSC does not need to have its trim codes computed, while the Silicon one does.

**Comment by lispler** [comment] 2016-09-09 14:07
Ok, I was a bit lazy there and just forced it to run boot_clk_trim_code_setup(). It is working now with the unmodified QMSI sources (same previously working app).

What I didn't notice before (but still see when using CLK_SYS_CRYSTAL_OSC and no trim setup) is that there seems to be some slight garbage on heavy usage. For example in the Zephyr dining philosophers example (concurrent threads printing to serial) there is an occasional transmission error.

Any hints for how to reset this trim data with a one-liner? It seems I have to fill 0x402f000 with 0xFF.

**Comment by lispler** [comment] 2016-09-09 14:18
Good point about CurieBSP. But really I like to work with Zephyr and QMSI, not so keen on a third SDK..

**Comment by lispler** [comment] 2016-09-09 14:46
FYI 'slight garbage' mentioned above also happens on D2000, changing the serial cable helped..

**Comment by jeez** [comment] 2016-09-09 17:43
@lispler good news then? Looks like a physical setup issue rather then a firmware one, right?

**Comment by lispler** [comment] 2016-09-10 00:46
Needed to reset trim data on flash, otherwise complete/unreadable junk output.
Apparently necessary on all Arduino/Genuino101.

**Comment by jeez** [comment] 2016-09-13 13:45
@dalessan good to keep the above in mind.

**Comment by jeez** [comment] 2016-09-13 13:47
@lispler since Arduino101 is still not a target board for the QMSI bootloader, I will close this for now, ok?

Soon the bootloader will live in https://github.com/quark-mcu/qm-bootloader instead. We can have an issue open there to track the request of having these boards supported in the future.

thanks for the investigation!

**Closed as completed by jeez** 2016-09-13 13:47 UTC
